! -*- f90 -*-
! ==============================================================================
! messy_mecca_dbl_box
! generated: {%TIMEDATE}
!
! this module is generated by imdpouble utility
!
! inter-configuration module
! level: boxmodel
! ZERO VERSION for compatibility
!
! [Gromov, MPI-C, 2007-2009]
! ==============================================================================

! - general doubling parameters (as conditional defines) -----------------------

! ?include 'messy_mecca_dbl_parameters.inc'

! -----------------------------------------------------------------------------

MODULE messy_mecca_dbl_box

  USE messy_mecca_kpp ! dp, ...

! configurations linked
! {$CONF_LIST} [%  USE messy_mecca_#%]

  IMPLICIT NONE

  PUBLIC mecca_dbl_emis
  PUBLIC mecca_dbl_postprocess
  PUBLIC mecca_dbl_resetPTs
  PUBLIC mecca_dbl_init
  PUBLIC mecca_dbl_result
  PUBLIC mecca_dbl_finish

! =============================================================================

CONTAINS

! -----------------------------------------------------------------------------

  SUBROUTINE mecca_dbl_emis
 
    IMPLICIT NONE
    
  END SUBROUTINE mecca_dbl_emis



! -----------------------------------------------------------------------------

  SUBROUTINE mecca_dbl_postprocess

    IMPLICIT NONE

  END SUBROUTINE mecca_dbl_postprocess



! -----------------------------------------------------------------------------
 
  SUBROUTINE mecca_dbl_resetPTs
  
    IMPLICIT NONE
    
  END SUBROUTINE mecca_dbl_resetPTs


! -----------------------------------------------------------------------------

  SUBROUTINE mecca_dbl_init

    IMPLICIT NONE

  END SUBROUTINE mecca_dbl_init



! -----------------------------------------------------------------------------

  SUBROUTINE mecca_dbl_result(model_time)
  
    IMPLICIT NONE
    
    REAL(dp), INTENT(IN) :: model_time
    
  END SUBROUTINE mecca_dbl_result



! ---------------------------------------------------------------------------

  SUBROUTINE mecca_dbl_finish

    IMPLICIT NONE
    
  END SUBROUTINE mecca_dbl_finish



! ---------------------------------------------------------------------------

END MODULE messy_mecca_dbl_box

! ***************************************************************************

