! -*- f90 -*-
! ==============================================================================
! messy_mecca_tag
! generated: {%TIMEDATE}
!
! This module is generated by imtag utility
!
! inter-configuration module: kinetics
!
! {$TAG_INFO} ! this is a template for isotopes configuration
!
! [Gromov, MPI-C, 2007-2008]
! ==============================================================================

! - general tagging parameters (as conditional defines) ------------------------

! INCLUDE 'messy_mecca_tag_parameters.inc'

! ------------------------------------------------------------------------------


MODULE messy_mecca_tag_box

  USE messy_mecca_kpp ! dp, ...
  
! common flow calculation, utils
! USE messy_mecca_tag_common

! configurations linked
! {$CONF_LIST} [%  USE messy_mecca_#%]

  IMPLICIT NONE

  PUBLIC tag_emis
  PUBLIC tag_process     ! substitutes _calctotals, _calcdeltas, _calcfractions
  PUBLIC tag_resetPTs
  PUBLIC tag_init
  PUBLIC tag_result
  PUBLIC tag_finish

! ==============================================================================

CONTAINS

! ------------------------------------------------------------------------------

  SUBROUTINE tag_emis
    IMPLICIT NONE
  END SUBROUTINE tag_emis
  
  SUBROUTINE tag_process(TSL, nstep, C, press, cair, temp)

    USE messy_main_constants_mem, ONLY: dp

    IMPLICIT NONE

    ! I/O
    REAL(dp), INTENT(IN)  :: C(:)
    REAL(dp), INTENT(IN)  :: press
    REAL(dp), INTENT(IN)  :: cair
    REAL(dp), INTENT(IN)  :: temp  
    REAL(dp), INTENT(IN) :: TSL      ! TSL = times_step_len value    
    INTEGER, INTENT(IN)  :: nstep

  END SUBROUTINE tag_process
  
  SUBROUTINE tag_resetPTs
    IMPLICIT NONE
  END SUBROUTINE tag_resetPTs

  SUBROUTINE tag_init
    IMPLICIT NONE
  END SUBROUTINE tag_init

  SUBROUTINE tag_result(model_time)
    IMPLICIT NONE
    REAL(dp), INTENT(IN) :: model_time
  END SUBROUTINE tag_result

  SUBROUTINE tag_finish
    IMPLICIT NONE
  END SUBROUTINE tag_finish


END MODULE messy_mecca_tag_box

! ******************************************************************************

