! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2.1_rs5 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : messy_mecca_kpp_Rates.f90
! Time                 : Thu Aug 26 14:15:50 2010
! Working directory    : /home/caaba/caaba_2.7b/mecca
! Equation file        : messy_mecca_kpp.kpp
! Output root filename : messy_mecca_kpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE messy_mecca_kpp_Rates

  USE messy_mecca_kpp_Parameters
  USE messy_mecca_kpp_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions


  ELEMENTAL REAL(dp) FUNCTION k_SIV_H2O2 (k_298,tdep,cHp,temp)
    ! special rate function for S(IV) + H2O2
    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(dp), INTENT(IN) :: cHp   ! c(H+)
    REAL(dp), INTENT(IN) :: temp  ! temperature
    INTRINSIC :: EXP
    k_SIV_H2O2 = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) &
      * cHp / (cHp+0.1_dp)
  END FUNCTION k_SIV_H2O2
  ELEMENTAL REAL(dp) FUNCTION k_3rd_iupac(temp,cair,k0_300K,n,kinf_300K,m,fc)
    ! IUPAC three body reaction formula (www.iupac-kinetic.ch.cam.ac.uk)
    INTRINSIC :: LOG10
    REAL(dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL,     INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL,     INTENT(IN) :: n         ! exponent for low pressure limit
    REAL,     INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL,     INTENT(IN) :: m         ! exponent for high pressure limit
    REAL,     INTENT(IN) :: fc        ! broadening factor (e.g. 0.45 or 0.6...)
    REAL                 :: nu        ! N
    REAL                 :: zt_help, k0_T, kinf_T, k_ratio
    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    nu      = 0.75-1.27*LOG10(fc)
    k_3rd_iupac = k0_T/(1._dp+k_ratio)* &
      fc**(1._dp/(1._dp+(LOG10(k_ratio)/nu)**2))
  END FUNCTION k_3rd_iupac
  ELEMENTAL REAL(dp) FUNCTION k_limited (k3rd,cHp)
    ! diffusion limitation caps 3rd order rate coefficients
    REAL(dp), INTENT(IN) :: k3rd  ! 3rd order rate coefficient
    REAL(dp), INTENT(IN) :: cHp   ! c(H+)
    REAL(dp), PARAMETER  :: DiffLimit = 1E10 ! diffusion limitation [M-1s-1]
    INTRINSIC :: EXP
    k_limited = 1._dp / ( 1._dp/k3rd + cHp/DiffLimit)
  END FUNCTION k_limited

! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE messy_mecca_kpp_Parameters
      !USE messy_mecca_kpp_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST


  USE messy_main_constants_mem ! atm2Pa, N_A, R_gas
  USE messy_cmn_photol_mem     ! IP_MAX, ip_*, jname
  ! end of USE statements
  !
  ! start of executable statements
  ! define some rate constants here if the expressions are too long
  ! for kpp or if they are used more than once
  k_HO2_HO2    = (1.5E-12*EXP(LOG(1.13)*mcexp(1))*EXP(19./temp)+1.7E-33*EXP(1000./temp)*cair)* & ! {1.5+-0.2}
                 (1.+1.4E-21*EXP(2200./temp)*C(ind_H2O))
  k_NO3_NO2    = k_3rd(temp,cair,2.0E-30,4.4,1.4E-12,0.7,0.6)*EXP(LOG(1.2)*mcexp(2))
  k_NO2_HO2    = k_3rd(temp,cair,2.0E-31,3.4,2.9E-12,1.1,0.6)*EXP(LOG(1.1)*mcexp(3))
  k_HNO3_OH    = 2.4E-14*EXP(460./temp) + 1./ &
                 ( 1./(6.5E-34*EXP(1335./temp)*cair) + &
                 1./(2.7E-17*EXP(2199./temp)) )*EXP(LOG(1.2)*mcexp(4))
  k_CH3OOH_OH  = 3.8E-12*EXP(200./temp)*EXP(LOG(1.4)*mcexp(5))
  k_CH3CO3_NO2 = k_3rd(temp,cair,9.7E-29,5.6,9.3E-12,1.5,0.6)*EXP(LOG(1.25)*mcexp(6))
  k_PAN_M      = k_CH3CO3_NO2/9.0E-29*EXP(-14000./temp)
  k_ClO_ClO    = k_3rd_iupac(temp,cair,2.0E-32*EXP(0.1*LOG(10.)*mcexp(7)), &
                 4.0,1.0E-11*EXP(0.3*LOG(10.)*mcexp(8)),0.0,0.45)*EXP(0.1*LOG(10.)*mcexp(9))
  ! JPL: k_ClO_ClO   = k_3rd(temp,cair,1.6E-32,4.5,2.0E-12,2.4,0.6)
  k_BrO_NO2    = k_3rd_iupac(temp,cair,4.7E-31*EXP(0.1*LOG(10.)*mcexp(10)),3.1,1.8E-11*EXP(0.1*LOG(10.)*mcexp(11)),0.0,0.4)
  ! JPL: k_BrO_NO2   = k_3rd(temp,cair,5.2E-31,3.2,6.9E-12,2.9,0.6)
  k_I_NO2      = k_3rd_iupac(temp,cair,3.0E-31*EXP(0.2*LOG(10.)*mcexp(12)),1.0,6.6E-11*EXP(0.3*LOG(10.)*mcexp(13)),0.0,0.63)
  ! for numerical reasons, the expression is multiplied by 1e30/1e30
  k_DMS_OH     = 1.E-9*EXP(5820./temp)*C(ind_O2)/ &
                 (1.E30+5.*EXP(6280./temp)*C(ind_O2))*EXP(0.30*LOG(10.)*mcexp(14))
  G7402a_yield = 0.8*EXP(LOG(1.25)*mcexp(15))/1.1 ! 0.8+-0.2
  ! mz_pj_20080812+
  k_O3s = (1.7E-12*EXP(-940./temp)) * C(ind_OH) &  ! <G2104>
        + (1.E-14*EXP(-490./temp)) * C(ind_HO2) &  ! <G2107>
        + jx(ip_O1D) * 2.2E-10 * C(ind_H2O) &      !
        / ( 3.2E-11*EXP(70./temp)*C(ind_O2)   &
           + 1.8E-11*EXP(110./temp)*C(ind_N2) &
           + 2.2E-10*C(ind_H2O) )
  ! mz_pj_20080812-
  KRO2NO  = 2.54E-12*EXP(LOG(1.25)*mcexp(16))*EXP(360./temp)
  KRO2HO2 = 2.91E-13*EXP(LOG(1.25)*mcexp(17))*EXP(1300./temp)
  KAPHO2  = 4.30E-13*EXP(LOG(1.25)*mcexp(18))*EXP(1040./temp) ! CH3CO3 + HO2
  KAPNO   = 8.10E-12*EXP(LOG(1.25)*mcexp(19))*EXP(270./temp)  ! CH3CO3 + NO
  KRO2NO3 = 2.50E-12*EXP(LOG(1.25)*mcexp(20))
  KNO3AL  = 1.4E-12*EXP(LOG(1.25)*mcexp(21))*EXP(-1900./temp)
  J_IC3H7NO3 = 3.7*jx(ip_PAN)*EXP(LOG(1.25)*mcexp(22))
  J_ACETOL   = 0.65*0.11*jx(ip_CHOH)*EXP(LOG(1.25)*mcexp(23))
  RO2 = 0.
  IF (ind_LISOPACO2>0)  RO2 = RO2 + C(ind_LISOPACO2)
  IF (ind_ISOPBO2>0)    RO2 = RO2 + C(ind_ISOPBO2)
  IF (ind_ISOPDO2>0)    RO2 = RO2 + C(ind_ISOPDO2)
  IF (ind_NISOPO2>0)    RO2 = RO2 + C(ind_NISOPO2)
  IF (ind_LHC4ACCO3>0)  RO2 = RO2 + C(ind_LHC4ACCO3)
  IF (ind_LC578O2>0)    RO2 = RO2 + C(ind_LC578O2)
  IF (ind_C59O2>0)      RO2 = RO2 + C(ind_C59O2)
  IF (ind_LNISO3>0)     RO2 = RO2 + C(ind_LNISO3)
  IF (ind_CH3O2>0)      RO2 = RO2 + C(ind_CH3O2)
  IF (ind_CH3CO3>0)     RO2 = RO2 + C(ind_CH3CO3)
  IF (ind_C2H5O2>0)     RO2 = RO2 + C(ind_C2H5O2)
  IF (ind_HOCH2CO3>0)   RO2 = RO2 + C(ind_HOCH2CO3)
  IF (ind_HYPROPO2>0)   RO2 = RO2 + C(ind_HYPROPO2)
  IF (ind_HCOCO3>0)     RO2 = RO2 + C(ind_HCOCO3)
  IF (ind_CO2H3CO3>0)   RO2 = RO2 + C(ind_CO2H3CO3)
  IF (ind_LHMVKABO2>0)  RO2 = RO2 + C(ind_LHMVKABO2)
  IF (ind_MACO3>0)      RO2 = RO2 + C(ind_MACO3)
  IF (ind_MACRO2>0)     RO2 = RO2 + C(ind_MACRO2)
  IF (ind_LMVKOHABO2>0) RO2 = RO2 + C(ind_LMVKOHABO2)
  IF (ind_PRONO3BO2>0)  RO2 = RO2 + C(ind_PRONO3BO2)
  IF (ind_HOCH2CH2O2>0) RO2 = RO2 + C(ind_HOCH2CH2O2)
  IF (ind_CH3COCH2O2>0) RO2 = RO2 + C(ind_CH3COCH2O2)
  IF (ind_IC3H7O2>0)    RO2 = RO2 + C(ind_IC3H7O2)
  IF (ind_LC4H9O2>0)    RO2 = RO2 + C(ind_LC4H9O2)
  IF (ind_LMEKO2>0)     RO2 = RO2 + C(ind_LMEKO2)

! End INLINED RCONST

  RCONST(1) = (3.3E-11*EXP(LOG(1.1)*mcexp(24))*EXP(55./temp))
  RCONST(2) = (6.E-34*EXP(LOG(1.1)*mcexp(25))*((temp/300.)**(-2.4))*cair)
  RCONST(3) = (k_3rd(temp,cair,4.4E-32,1.3,4.7E-11,0.2,0.6)*EXP(LOG(1.3)*mcexp(26)))
  RCONST(4) = (1.7E-12*EXP(LOG(1.2)*mcexp(27))*EXP(-940./temp))
  RCONST(5) = (2.8E-12*EXP(LOG(1.05)*mcexp(28))*EXP(-1800./temp))
  RCONST(6) = (1.E-14*EXP(LOG(1.15)*mcexp(29))*EXP(-490./temp))
  RCONST(7) = (4.8E-11*EXP(LOG(1.25)*mcexp(30))*EXP(250./temp))
  RCONST(8) = (k_HO2_HO2)
  RCONST(9) = (1.63E-10*EXP(LOG(1.15)*mcexp(31))*EXP(60./temp))
  RCONST(10) = (1.8E-12*EXP(LOG(1.25)*mcexp(32)))
  RCONST(11) = (2.15E-11*EXP(LOG(1.10)*mcexp(33))*EXP(110./temp))
  RCONST(12) = (3.E-12*EXP(LOG(1.1)*mcexp(34))*EXP(-1500./temp))
  RCONST(13) = (1.2E-13*EXP(LOG(1.15)*mcexp(35))*EXP(-2450./temp))
  RCONST(14) = (1.5E-11*EXP(LOG(1.3)*mcexp(36))*EXP(170./temp))
  RCONST(15) = (k_NO3_NO2)
  RCONST(16) = (k_NO3_NO2/(2.7E-27*EXP(LOG(1.2)*mcexp(37))*EXP(11000./temp)))
  RCONST(17) = (k_3rd(temp,cair,7.0E-31,2.6,3.6E-11,0.1,0.6)*EXP(LOG(1.2)*mcexp(38)))
  RCONST(18) = (3.5E-12*EXP(250./temp)*EXP(LOG(1.15)*mcexp(39)))
  RCONST(19) = (k_3rd(temp,cair,1.8E-30,3.0,2.8E-11,0.,0.6)*EXP(LOG(1.3)*mcexp(40)))
  RCONST(20) = (k_NO2_HO2)
  RCONST(21) = (3.5E-12*EXP(LOG(1.5)*mcexp(41)))
  RCONST(22) = (1.8E-11*EXP(LOG(1.5)*mcexp(42))*EXP(-390./temp))
  RCONST(23) = (k_HNO3_OH)
  RCONST(24) = (k_NO2_HO2/(2.1E-27*EXP(LOG(1.3)*mcexp(43))*EXP(10900./temp)))
  RCONST(25) = (1.3E-12*EXP(LOG(1.3)*mcexp(44))*EXP(380./temp))
  RCONST(26) = (1.7E-12*EXP(LOG(1.25)*mcexp(45))*EXP(-710./temp))
  RCONST(27) = (4.3E-12*EXP(LOG(1.25)*mcexp(46))*EXP(-930./temp))
  RCONST(28) = (4.8E-07*EXP(LOG(1.25)*mcexp(47))*EXP(-628./temp)*temp**(-1.32))
  RCONST(29) = (9.4E-09*EXP(LOG(1.25)*mcexp(48))*EXP(-356./temp)*temp**(-1.12))
  RCONST(30) = (1.92E-12*EXP(LOG(1.25)*mcexp(49))*((temp/298.)**(-1.5)))
  RCONST(31) = (1.41E-11*EXP(LOG(1.25)*mcexp(50))*((temp/298.)**(-1.5)))
  RCONST(32) = (1.2E-11*EXP(LOG(1.25)*mcexp(51))*((temp/298.)**(-2.0)))
  RCONST(33) = (0.8E-11*EXP(LOG(1.25)*mcexp(52))*((temp/298.)**(-2.0)))
  RCONST(34) = (1.2E-14*EXP(LOG(1.25)*mcexp(53)))
  RCONST(35) = (1.3E3*EXP(LOG(1.25)*mcexp(54)))
  RCONST(36) = (8.0E-11*EXP(LOG(1.25)*mcexp(55))*EXP(-500./temp))
  RCONST(37) = (1.66E-12*EXP(LOG(1.25)*mcexp(56))*EXP(-1500./temp))
  RCONST(38) = (1.0E-12*EXP(LOG(1.25)*mcexp(57))*EXP(-1000./temp))
  RCONST(39) = (1.66E-12*EXP(LOG(1.25)*mcexp(58)))
  RCONST(40) = (4.13E-11*EXP(LOG(1.25)*mcexp(59))*EXP(-2138./temp))
  RCONST(41) = (3.65E-14*EXP(LOG(1.25)*mcexp(60))*EXP(-4600./temp))
  RCONST(42) = (1.85E-20*EXP(LOG(1.2)*mcexp(61))*EXP(2.82*log(temp)-987./temp))
  RCONST(43) = (2.9E-12*EXP(LOG(1.10)*mcexp(62))*EXP(-345./temp))
  RCONST(44) = (4.1E-13*EXP(LOG(1.3)*mcexp(63))*EXP(750./temp))
  RCONST(45) = (2.8E-12*EXP(LOG(1.15)*mcexp(64))*EXP(300./temp))
  RCONST(46) = (1.3E-12*EXP(0.3*LOG(10.)*mcexp(65)))
  RCONST(47) = (2.*RO2*9.5E-14*EXP(LOG(1.2)*mcexp(66))*EXP(390./temp)/(1.+1./26.2*EXP(LOG(1.25)*mcexp(67))*EXP(1130./tem&
                 &p)))
  RCONST(48) = (2.*RO2*9.5E-14*EXP(LOG(1.2)*mcexp(68))*EXP(390./temp)/(1.+26.2*EXP(LOG(1.25)*mcexp(69))*EXP(-1130./temp)&
                 &))
  RCONST(49) = (k_CH3OOH_OH)
  RCONST(50) = (9.52E-18*EXP(LOG(1.05)*mcexp(70))*EXP(2.03*log(temp)+636./temp))
  RCONST(51) = (3.4E-13*EXP(LOG(1.3)*mcexp(71))*EXP(-1900./temp))
  RCONST(52) = ((1.57E-13+cair*3.54E-33)*EXP(LOG(1.15)*mcexp(72)))
  RCONST(53) = (4.0E-13*EXP(LOG(1.2)*mcexp(73)))
  RCONST(54) = (1.49E-17*EXP(LOG(1.25)*mcexp(74))*temp*temp*EXP(-499./temp))
  RCONST(55) = (1.2E-14*EXP(LOG(1.25)*mcexp(75))*EXP(-2630./temp))
  RCONST(56) = (k_3rd(temp,cair,1.0E-28,4.5,8.8E-12,0.85,0.6)*EXP(LOG(1.25)*mcexp(76)))
  RCONST(57) = (7.5E-13*EXP(LOG(1.25)*mcexp(77))*EXP(700./temp))
  RCONST(58) = (2.6E-12*EXP(LOG(1.25)*mcexp(78))*EXP(365./temp))
  RCONST(59) = (2.3E-12*EXP(LOG(1.25)*mcexp(79)))
  RCONST(60) = (3.1E-13*EXP(LOG(1.25)*mcexp(80))*RO2)
  RCONST(61) = (0.6*k_CH3OOH_OH+8.01E-12)
  RCONST(62) = (4.4E-12*EXP(0.08*LOG(10.)*mcexp(81))*EXP(365./temp))
  RCONST(63) = (KNO3AL)
  RCONST(64) = (4.2E-14*EXP(0.15*LOG(10.)*mcexp(82))*EXP(855./temp))
  RCONST(65) = (4.3E-13*EXP(LOG(1.25)*mcexp(83))*EXP(1040./temp)/(1.+1./37.*EXP(660./temp)))
  RCONST(66) = (4.3E-13*EXP(LOG(1.25)*mcexp(84))*EXP(1040./temp)/(1.+37.*EXP(-660./temp)))
  RCONST(67) = (8.1E-12*EXP(LOG(1.25)*mcexp(85))*EXP(270./temp))
  RCONST(68) = (k_CH3CO3_NO2)
  RCONST(69) = (4.E-12*EXP(LOG(1.25)*mcexp(86)))
  RCONST(70) = (1.00E-11*EXP(LOG(1.25)*mcexp(87))*RO2)
  RCONST(71) = (0.6*k_CH3OOH_OH)
  RCONST(72) = (9.50E-13*EXP(LOG(1.25)*mcexp(88))*EXP(-650./temp))
  RCONST(73) = (k_PAN_M)
  RCONST(74) = (k_3rd(temp,cair,5.5e-30,0.0,8.3e-13,-2.,0.6)*EXP(LOG(1.25)*mcexp(89)))
  RCONST(75) = (1.00E-11*EXP(LOG(1.25)*mcexp(90)))
  RCONST(76) = (KNO3AL)
  RCONST(77) = (1.00E-11*EXP(LOG(1.25)*mcexp(91))*RO2)
  RCONST(78) = (KAPHO2)
  RCONST(79) = (KAPNO)
  RCONST(80) = (k_CH3CO3_NO2)
  RCONST(81) = (KRO2NO3*1.60)
  RCONST(82) = (2.73E-12*EXP(LOG(1.25)*mcexp(92)))
  RCONST(83) = (6.19E-12*EXP(LOG(1.25)*mcexp(93)))
  RCONST(84) = (k_PAN_M)
  RCONST(85) = (1.12E-12*EXP(LOG(1.25)*mcexp(94)))
  RCONST(86) = (1.14E-11*EXP(LOG(1.25)*mcexp(95)))
  RCONST(87) = (KNO3AL)
  RCONST(88) = (1.00E-11*EXP(LOG(1.25)*mcexp(96))*RO2)
  RCONST(89) = (KAPHO2)
  RCONST(90) = (KAPNO)
  RCONST(91) = (KRO2NO3*1.60)
  RCONST(92) = (1.23E-11*EXP(LOG(1.25)*mcexp(97)))
  RCONST(93) = (1.58E-11*EXP(LOG(1.25)*mcexp(98)))
  RCONST(94) = (2.00E-12*EXP(LOG(1.25)*mcexp(99))*RO2)
  RCONST(95) = (KRO2NO)
  RCONST(96) = (2.00E-13*EXP(LOG(1.25)*mcexp(100))*EXP(1250./temp))
  RCONST(97) = (8.40E-13*EXP(LOG(1.25)*mcexp(101)))
  RCONST(98) = (0.6*k_CH3OOH_OH)
  RCONST(99) = (1.38E-11*EXP(LOG(1.25)*mcexp(102)))
  RCONST(100) = (6.00E-14*EXP(LOG(1.25)*mcexp(103))*EXP(-550./temp)*C(ind_O2))
  RCONST(101) = (9.50E13*EXP(LOG(1.25)*mcexp(104))*EXP(-5988./temp))
  RCONST(102) = (7.70E-12*EXP(LOG(1.25)*mcexp(105)))
  RCONST(103) = (1.55E-17*EXP(LOG(1.25)*mcexp(106))*temp*temp*EXP(-61./temp))
  RCONST(104) = (6.5E-15*EXP(LOG(1.25)*mcexp(107))*EXP(-1900./temp))
  RCONST(105) = (k_3rd(temp,cair,8.E-27,3.5,3.E-11,0.,0.5)*EXP(LOG(1.25)*mcexp(108)))
  RCONST(106) = (4.6E-13*EXP(LOG(1.25)*mcexp(109))*EXP(-1155./temp))
  RCONST(107) = (1.9E-13*EXP(LOG(1.25)*mcexp(110))*EXP(1300./temp))
  RCONST(108) = (2.7E-12*EXP(LOG(1.25)*mcexp(111))*EXP(360./temp))
  RCONST(109) = (4.E-14*EXP(LOG(1.25)*mcexp(112))*RO2)
  RCONST(110) = (1.66E-11*EXP(LOG(1.25)*mcexp(113))+0.6*k_CH3OOH_OH)
  RCONST(111) = ((1.33E-13+3.82E-11*EXP(-2000./temp))*EXP(LOG(1.25)*mcexp(114)))
  RCONST(112) = (8.6E-13*EXP(LOG(1.25)*mcexp(115))*EXP(700./temp))
  RCONST(113) = (2.9E-12*EXP(LOG(1.25)*mcexp(116))*EXP(300./temp))
  RCONST(114) = (7.5E-13*EXP(LOG(1.25)*mcexp(117))*EXP(500./temp)*2.*RO2)
  RCONST(115) = (0.6*k_CH3OOH_OH)
  RCONST(116) = (8.39E-12*EXP(LOG(1.25)*mcexp(118)))
  RCONST(117) = (3.E-12*EXP(LOG(1.25)*mcexp(119)))
  RCONST(118) = (8.4E-13*EXP(LOG(1.25)*mcexp(120))*EXP(830./temp))
  RCONST(119) = (6.2E-13*EXP(LOG(1.25)*mcexp(121))*EXP(-230./temp))
  RCONST(120) = (KRO2NO3)
  RCONST(121) = (8.80E-13*EXP(LOG(1.25)*mcexp(122))*RO2)
  RCONST(122) = (KRO2HO2*0.520)
  RCONST(123) = (KRO2NO)
  RCONST(124) = (KRO2NO3)
  RCONST(125) = (1.90E-12*EXP(LOG(1.25)*mcexp(123))*EXP(190./temp))
  RCONST(126) = (2.44E-11*EXP(LOG(1.25)*mcexp(124)))
  RCONST(127) = (KRO2HO2*0.520)
  RCONST(128) = (KRO2NO)
  RCONST(129) = (KRO2NO3)
  RCONST(130) = (1.90E-12*EXP(LOG(1.25)*mcexp(125))*EXP(190./temp))
  RCONST(131) = (3.47E-12*EXP(LOG(1.25)*mcexp(126)))
  RCONST(132) = (KNO3AL*2.4)
  RCONST(133) = (1.30E-13*EXP(LOG(1.25)*mcexp(127)))
  RCONST(134) = (1.44E-11*EXP(LOG(1.25)*mcexp(128)))
  RCONST(135) = (KNO3AL*2.4)
  RCONST(136) = (2.89E-12*EXP(LOG(1.25)*mcexp(129)))
  RCONST(137) = (1.81E-17*EXP(LOG(1.25)*mcexp(130))*temp*temp*EXP(114./temp))
  RCONST(138) = (2.5E-13*EXP(LOG(1.25)*mcexp(131))*RO2)
  RCONST(139) = (KRO2HO2*0.625)
  RCONST(140) = (KRO2NO)
  RCONST(141) = (2.636E-11*EXP(LOG(1.25)*mcexp(132)))
  RCONST(142) = (7.51E-16*EXP(LOG(1.25)*mcexp(133))*EXP(-1521./temp))
  RCONST(143) = (4.13E-12*EXP(LOG(1.25)*mcexp(134))*EXP(452./temp))
  RCONST(144) = (3.24E-18*EXP(LOG(1.25)*mcexp(135))*temp*temp*EXP(414./temp))
  RCONST(145) = (KRO2HO2*0.625)
  RCONST(146) = (KRO2NO)
  RCONST(147) = (3.786E-11*EXP(LOG(1.25)*mcexp(136)))
  RCONST(148) = (9.598E-13*EXP(LOG(1.25)*mcexp(137)))
  RCONST(149) = (3.2E-11*EXP(LOG(1.25)*mcexp(138)))
  RCONST(150) = (k_PAN_M)
  RCONST(151) = (1.483E-12*EXP(LOG(1.25)*mcexp(139))*RO2)
  RCONST(152) = (1.86E-11*EXP(LOG(1.25)*mcexp(140))*EXP(175./temp))
  RCONST(153) = (1.36E-15*EXP(LOG(1.25)*mcexp(141))*EXP(-2112./temp))
  RCONST(154) = (KNO3AL*2.0)
  RCONST(155) = (1.00E-11*EXP(LOG(1.25)*mcexp(142))*RO2)
  RCONST(156) = (KAPHO2)
  RCONST(157) = (8.70E-12*EXP(LOG(1.25)*mcexp(143))*EXP(290./temp))
  RCONST(158) = (k_CH3CO3_NO2)
  RCONST(159) = (KRO2NO3*1.60)
  RCONST(160) = (9.20E-14*EXP(LOG(1.25)*mcexp(144))*RO2)
  RCONST(161) = (KRO2HO2*0.625)
  RCONST(162) = (KRO2NO)
  RCONST(163) = (KRO2NO3)
  RCONST(164) = (2.82E-11*EXP(LOG(1.25)*mcexp(145)))
  RCONST(165) = (2.46E-11*EXP(LOG(1.25)*mcexp(146)))
  RCONST(166) = (1.51E-11*EXP(LOG(1.25)*mcexp(147)))
  RCONST(167) = (1.87E-11*EXP(LOG(1.25)*mcexp(148)))
  RCONST(168) = ((.3*2.00E-12+.7*8.80E-13)*EXP(LOG(1.25)*mcexp(149))*RO2)
  RCONST(169) = (KRO2HO2*0.625)
  RCONST(170) = (KRO2NO)
  RCONST(171) = (KRO2NO3)
  RCONST(172) = (4.496E-11*EXP(LOG(1.25)*mcexp(150)))
  RCONST(173) = (4.60E-12*EXP(LOG(1.25)*mcexp(151))*EXP(452./temp))
  RCONST(174) = (7.51E-16*EXP(LOG(1.25)*mcexp(152))*EXP(-1521./temp))
  RCONST(175) = ((0.3*2.00E-12+0.7*8.80E-13)*EXP(LOG(1.25)*mcexp(153))*RO2)
  RCONST(176) = (KRO2HO2*0.625)
  RCONST(177) = (KRO2NO)
  RCONST(178) = (KRO2NO3)
  RCONST(179) = (5.98E-11*EXP(LOG(1.25)*mcexp(154)))
  RCONST(180) = (2.45E-11*EXP(LOG(1.25)*mcexp(155)))
  RCONST(181) = (KNO3AL*4.0)
  RCONST(182) = (1.00E-11*EXP(LOG(1.25)*mcexp(156))*RO2)
  RCONST(183) = (KAPHO2)
  RCONST(184) = (KAPNO)
  RCONST(185) = (KRO2NO3*1.60)
  RCONST(186) = (7.34E-12*EXP(LOG(1.25)*mcexp(157)))
  RCONST(187) = (1.88E-11*EXP(LOG(1.25)*mcexp(158)))
  RCONST(188) = (7.86E-15*EXP(LOG(1.25)*mcexp(159))*EXP(-1913./temp))
  RCONST(189) = (2.54E-11*EXP(LOG(1.25)*mcexp(160))*EXP(410./temp))
  RCONST(190) = (3.03E-12*EXP(LOG(1.25)*mcexp(161))*EXP(-446./temp))
  RCONST(191) = (2.4E-12*EXP(LOG(1.25)*mcexp(162))*RO2)
  RCONST(192) = (0.706*KRO2HO2)
  RCONST(193) = (KRO2NO)
  RCONST(194) = (KRO2NO3)
  RCONST(195) = (1.07E-10*EXP(LOG(1.25)*mcexp(163)))
  RCONST(196) = (9.30E-11*EXP(LOG(1.25)*mcexp(164)))
  RCONST(197) = (8.91E-11*EXP(LOG(1.25)*mcexp(165)))
  RCONST(198) = (8.E-13*EXP(LOG(1.25)*mcexp(166))*RO2)
  RCONST(199) = (0.706*KRO2HO2)
  RCONST(200) = (KRO2NO)
  RCONST(201) = (KRO2NO3)
  RCONST(202) = (4.2E-11*EXP(LOG(1.25)*mcexp(167)))
  RCONST(203) = (3.85E-11*EXP(LOG(1.25)*mcexp(168)))
  RCONST(204) = (3.55E-11*EXP(LOG(1.25)*mcexp(169)))
  RCONST(205) = (2.9E-12*EXP(LOG(1.25)*mcexp(170))*RO2)
  RCONST(206) = (0.706*KRO2HO2)
  RCONST(207) = (KRO2NO)
  RCONST(208) = (KRO2NO3)
  RCONST(209) = (1.07E-10*EXP(LOG(1.25)*mcexp(171)))
  RCONST(210) = (7.38E-11*EXP(LOG(1.25)*mcexp(172)))
  RCONST(211) = (6.1E-11*EXP(LOG(1.25)*mcexp(173)))
  RCONST(212) = (1.3E-12*EXP(LOG(1.25)*mcexp(174))*RO2)
  RCONST(213) = (.706*KRO2HO2)
  RCONST(214) = (KRO2NO)
  RCONST(215) = (KRO2NO3)
  RCONST(216) = (1.03E-10*EXP(LOG(1.25)*mcexp(175)))
  RCONST(217) = (4.16E-11*EXP(LOG(1.25)*mcexp(176)))
  RCONST(218) = (2.40E-17*EXP(LOG(1.25)*mcexp(177)))
  RCONST(219) = (KNO3AL*4.25)
  RCONST(220) = (.5*.706*KRO2HO2+.5*KAPHO2)
  RCONST(221) = (.5*KAPNO+.5*KRO2NO)
  RCONST(222) = (1.3*KRO2NO3)
  RCONST(223) = (2.65E-11*EXP(LOG(1.25)*mcexp(178)))
  RCONST(224) = (4.52E-11*EXP(LOG(1.25)*mcexp(179)))
  RCONST(225) = (2.40E-17*EXP(LOG(1.25)*mcexp(180)))
  RCONST(226) = (KNO3AL*4.25)
  RCONST(227) = (9.20E-14*EXP(LOG(1.25)*mcexp(181))*RO2)
  RCONST(228) = (KRO2HO2*0.706)
  RCONST(229) = (KRO2NO)
  RCONST(230) = (KRO2NO3)
  RCONST(231) = (3.16E-11*EXP(LOG(1.25)*mcexp(182)))
  RCONST(232) = (1.00E-11*EXP(LOG(1.25)*mcexp(183))*RO2)
  RCONST(233) = (KAPHO2)
  RCONST(234) = (KAPNO)
  RCONST(235) = (k_CH3CO3_NO2)
  RCONST(236) = (1.6*KRO2NO3)
  RCONST(237) = (2.52E-11*EXP(LOG(1.25)*mcexp(184)))
  RCONST(238) = (2.88E-11*EXP(LOG(1.25)*mcexp(185)))
  RCONST(239) = (k_PAN_M)
  RCONST(240) = (2.52E-11*EXP(LOG(1.25)*mcexp(186)))
  RCONST(241) = (3.81E-11*EXP(LOG(1.25)*mcexp(187)))
  RCONST(242) = (9.20E-14*EXP(LOG(1.25)*mcexp(188))*RO2)
  RCONST(243) = (KRO2HO2*0.706)
  RCONST(244) = (KRO2NO)
  RCONST(245) = (KRO2NO3)
  RCONST(246) = (9.7E-12*EXP(LOG(1.25)*mcexp(189)))
  RCONST(247) = (jx(ip_O2)*EXP(LOG(1.25)*mcexp(190)))
  RCONST(248) = (jx(ip_O1D)*EXP(LOG(1.25)*mcexp(191)))
  RCONST(249) = (jx(ip_O3P)*EXP(LOG(1.25)*mcexp(192)))
  RCONST(250) = (jx(ip_H2O2)*EXP(LOG(1.25)*mcexp(193)))
  RCONST(251) = (jx(ip_NO2)*EXP(LOG(1.25)*mcexp(194)))
  RCONST(252) = (jx(ip_NO2O)*EXP(LOG(1.25)*mcexp(195)))
  RCONST(253) = (jx(ip_NOO2)*EXP(LOG(1.25)*mcexp(196)))
  RCONST(254) = (jx(ip_N2O5)*EXP(LOG(1.25)*mcexp(197)))
  RCONST(255) = (jx(ip_HONO)*EXP(LOG(1.25)*mcexp(198)))
  RCONST(256) = (jx(ip_HNO3)*EXP(LOG(1.25)*mcexp(199)))
  RCONST(257) = (jx(ip_HNO4)*EXP(LOG(1.25)*mcexp(200)))
  RCONST(258) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(201)))
  RCONST(259) = (jx(ip_COH2)*EXP(LOG(1.25)*mcexp(202)))
  RCONST(260) = (jx(ip_CHOH)*EXP(LOG(1.25)*mcexp(203)))
  RCONST(261) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(204)))
  RCONST(262) = (jx(ip_CH3CHO)*EXP(LOG(1.25)*mcexp(205)))
  RCONST(263) = (jx(ip_CH3CO3H)*EXP(LOG(1.25)*mcexp(206)))
  RCONST(264) = (jx(ip_PAN)*EXP(LOG(1.25)*mcexp(207)))
  RCONST(265) = (jx(ip_HOCH2CHO)*EXP(LOG(1.25)*mcexp(208)))
  RCONST(266) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(209)))
  RCONST(267) = (jx(ip_PAN)*EXP(LOG(1.25)*mcexp(210)))
  RCONST(268) = (jx(ip_GLYOX)*EXP(LOG(1.25)*mcexp(211)))
  RCONST(269) = (jx(ip_MGLYOX)*EXP(LOG(1.25)*mcexp(212)))
  RCONST(270) = ((jx(ip_CH3OOH)+jx(ip_HOCH2CHO))*EXP(LOG(1.25)*mcexp(213)))
  RCONST(271) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(214)))
  RCONST(272) = (J_IC3H7NO3)
  RCONST(273) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(215)))
  RCONST(274) = (jx(ip_CH3COCH3)*EXP(LOG(1.25)*mcexp(216)))
  RCONST(275) = (J_ACETOL)
  RCONST(276) = (jx(ip_MGLYOX)*EXP(LOG(1.25)*mcexp(217)))
  RCONST(277) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(218))+J_ACETOL)
  RCONST(278) = (J_IC3H7NO3)
  RCONST(279) = (J_IC3H7NO3+jx(ip_CH3COCH3)*EXP(LOG(1.25)*mcexp(219)))
  RCONST(280) = (jx(ip_MGLYOX)*EXP(LOG(1.25)*mcexp(220)))
  RCONST(281) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(221)))
  RCONST(282) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(222)))
  RCONST(283) = (jx(ip_MGLYOX)*EXP(LOG(1.25)*mcexp(223)))
  RCONST(284) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(224)))
  RCONST(285) = (jx(ip_MVK)*EXP(LOG(1.25)*mcexp(225)))
  RCONST(286) = (0.42*jx(ip_CHOH)*EXP(LOG(1.25)*mcexp(226)))
  RCONST(287) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(227)))
  RCONST(288) = (2.15*jx(ip_MGLYOX)*EXP(LOG(1.25)*mcexp(228)))
  RCONST(289) = (J_IC3H7NO3)
  RCONST(290) = (jx(ip_PAN)*EXP(LOG(1.25)*mcexp(229)))
  RCONST(291) = (J_ACETOL+jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(230)))
  RCONST(292) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(231)))
  RCONST(293) = (J_ACETOL)
  RCONST(294) = (jx(ip_MACR)*EXP(LOG(1.25)*mcexp(232)))
  RCONST(295) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(233)))
  RCONST(296) = (2.77*jx(ip_HOCH2CHO)*EXP(LOG(1.25)*mcexp(234)))
  RCONST(297) = (2.77*jx(ip_HOCH2CHO)*EXP(LOG(1.25)*mcexp(235)))
  RCONST(298) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(236)))
  RCONST(299) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(237)))
  RCONST(300) = (jx(ip_MVK)*EXP(LOG(1.25)*mcexp(238)))
  RCONST(301) = (jx(ip_HOCH2CHO)*EXP(LOG(1.25)*mcexp(239)))
  RCONST(302) = (J_ACETOL)
  RCONST(303) = (2.15*jx(ip_MGLYOX)*EXP(LOG(1.25)*mcexp(240)))
  RCONST(304) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(241)))
  RCONST(305) = (0.59*J_IC3H7NO3)
  RCONST(306) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(242)))
  RCONST(307) = (2.84*J_IC3H7NO3)
  RCONST(308) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(243)))
  RCONST(309) = (J_IC3H7NO3)
  RCONST(310) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(244)))
  RCONST(311) = (jx(ip_MACR)*EXP(LOG(1.25)*mcexp(245)))
  RCONST(312) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(246)))
  RCONST(313) = (jx(ip_MACR)*EXP(LOG(1.25)*mcexp(247)))
  RCONST(314) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(248)))
  RCONST(315) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(249)))
  RCONST(316) = (jx(ip_PAN)*EXP(LOG(1.25)*mcexp(250)))
  RCONST(317) = (0.5*jx(ip_MVK)*EXP(LOG(1.25)*mcexp(251)))
  RCONST(318) = (J_ACETOL+jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(252)))
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE messy_mecca_kpp_Global

  RCONST(247) = (jx(ip_O2)*EXP(LOG(1.25)*mcexp(190)))
  RCONST(248) = (jx(ip_O1D)*EXP(LOG(1.25)*mcexp(191)))
  RCONST(249) = (jx(ip_O3P)*EXP(LOG(1.25)*mcexp(192)))
  RCONST(250) = (jx(ip_H2O2)*EXP(LOG(1.25)*mcexp(193)))
  RCONST(251) = (jx(ip_NO2)*EXP(LOG(1.25)*mcexp(194)))
  RCONST(252) = (jx(ip_NO2O)*EXP(LOG(1.25)*mcexp(195)))
  RCONST(253) = (jx(ip_NOO2)*EXP(LOG(1.25)*mcexp(196)))
  RCONST(254) = (jx(ip_N2O5)*EXP(LOG(1.25)*mcexp(197)))
  RCONST(255) = (jx(ip_HONO)*EXP(LOG(1.25)*mcexp(198)))
  RCONST(256) = (jx(ip_HNO3)*EXP(LOG(1.25)*mcexp(199)))
  RCONST(257) = (jx(ip_HNO4)*EXP(LOG(1.25)*mcexp(200)))
  RCONST(258) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(201)))
  RCONST(259) = (jx(ip_COH2)*EXP(LOG(1.25)*mcexp(202)))
  RCONST(260) = (jx(ip_CHOH)*EXP(LOG(1.25)*mcexp(203)))
  RCONST(261) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(204)))
  RCONST(262) = (jx(ip_CH3CHO)*EXP(LOG(1.25)*mcexp(205)))
  RCONST(263) = (jx(ip_CH3CO3H)*EXP(LOG(1.25)*mcexp(206)))
  RCONST(264) = (jx(ip_PAN)*EXP(LOG(1.25)*mcexp(207)))
  RCONST(265) = (jx(ip_HOCH2CHO)*EXP(LOG(1.25)*mcexp(208)))
  RCONST(266) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(209)))
  RCONST(267) = (jx(ip_PAN)*EXP(LOG(1.25)*mcexp(210)))
  RCONST(268) = (jx(ip_GLYOX)*EXP(LOG(1.25)*mcexp(211)))
  RCONST(269) = (jx(ip_MGLYOX)*EXP(LOG(1.25)*mcexp(212)))
  RCONST(270) = ((jx(ip_CH3OOH)+jx(ip_HOCH2CHO))*EXP(LOG(1.25)*mcexp(213)))
  RCONST(271) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(214)))
  RCONST(272) = (J_IC3H7NO3)
  RCONST(273) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(215)))
  RCONST(274) = (jx(ip_CH3COCH3)*EXP(LOG(1.25)*mcexp(216)))
  RCONST(275) = (J_ACETOL)
  RCONST(276) = (jx(ip_MGLYOX)*EXP(LOG(1.25)*mcexp(217)))
  RCONST(277) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(218))+J_ACETOL)
  RCONST(278) = (J_IC3H7NO3)
  RCONST(279) = (J_IC3H7NO3+jx(ip_CH3COCH3)*EXP(LOG(1.25)*mcexp(219)))
  RCONST(280) = (jx(ip_MGLYOX)*EXP(LOG(1.25)*mcexp(220)))
  RCONST(281) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(221)))
  RCONST(282) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(222)))
  RCONST(283) = (jx(ip_MGLYOX)*EXP(LOG(1.25)*mcexp(223)))
  RCONST(284) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(224)))
  RCONST(285) = (jx(ip_MVK)*EXP(LOG(1.25)*mcexp(225)))
  RCONST(286) = (0.42*jx(ip_CHOH)*EXP(LOG(1.25)*mcexp(226)))
  RCONST(287) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(227)))
  RCONST(288) = (2.15*jx(ip_MGLYOX)*EXP(LOG(1.25)*mcexp(228)))
  RCONST(289) = (J_IC3H7NO3)
  RCONST(290) = (jx(ip_PAN)*EXP(LOG(1.25)*mcexp(229)))
  RCONST(291) = (J_ACETOL+jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(230)))
  RCONST(292) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(231)))
  RCONST(293) = (J_ACETOL)
  RCONST(294) = (jx(ip_MACR)*EXP(LOG(1.25)*mcexp(232)))
  RCONST(295) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(233)))
  RCONST(296) = (2.77*jx(ip_HOCH2CHO)*EXP(LOG(1.25)*mcexp(234)))
  RCONST(297) = (2.77*jx(ip_HOCH2CHO)*EXP(LOG(1.25)*mcexp(235)))
  RCONST(298) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(236)))
  RCONST(299) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(237)))
  RCONST(300) = (jx(ip_MVK)*EXP(LOG(1.25)*mcexp(238)))
  RCONST(301) = (jx(ip_HOCH2CHO)*EXP(LOG(1.25)*mcexp(239)))
  RCONST(302) = (J_ACETOL)
  RCONST(303) = (2.15*jx(ip_MGLYOX)*EXP(LOG(1.25)*mcexp(240)))
  RCONST(304) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(241)))
  RCONST(305) = (0.59*J_IC3H7NO3)
  RCONST(306) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(242)))
  RCONST(307) = (2.84*J_IC3H7NO3)
  RCONST(308) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(243)))
  RCONST(309) = (J_IC3H7NO3)
  RCONST(310) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(244)))
  RCONST(311) = (jx(ip_MACR)*EXP(LOG(1.25)*mcexp(245)))
  RCONST(312) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(246)))
  RCONST(313) = (jx(ip_MACR)*EXP(LOG(1.25)*mcexp(247)))
  RCONST(314) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(248)))
  RCONST(315) = (jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(249)))
  RCONST(316) = (jx(ip_PAN)*EXP(LOG(1.25)*mcexp(250)))
  RCONST(317) = (0.5*jx(ip_MVK)*EXP(LOG(1.25)*mcexp(251)))
  RCONST(318) = (J_ACETOL+jx(ip_CH3OOH)*EXP(LOG(1.25)*mcexp(252)))
      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE messy_mecca_kpp_Rates

