! ==============================================================================
! {%DBL}_box
! generated: {%TIMEDATE}
!
! this module is automaticly generated by imdouble utility
! contains: some maintenance routines for budgeting configurations (isotopes)
! level: boxmodel
!
! {$DBL_INFO} ! this is a template file for imdouble utility
!
! [Gromov, MPIC, 2007-2008]
! ==============================================================================

! - general doubling parameters (as conditional defines) -----------------------

#include "{%CMODEL}_dbl_parameters.inc"

! ------------------------------------------------------------------------------

! {$CONF_PARAM}

MODULE messy_mecca_{%DBL}_box

  USE messy_mecca_kpp     ! dp, ... nreact, nspec, ind_*, SPC_NAMES, EQN_TAGS
  USE caaba_io,           ONLY: open_output_file, write_output_file, close_file
  USE caaba_mem,          ONLY: C, cair, press

  USE {%CMODEL}_dbl_common_box

  IMPLICIT NONE

! netcdf handle for deltas, conc., etc. output
  INTEGER :: ncid_{%DBL}

->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:C}
! reference standart ratio for 13C, V-PDB
  REAL(dp), PARAMETER :: VPDB_13C     = 1123.72E-05_dp
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:C}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:O}
! reference standart ratio for 17O, 18O, V-SMOW
  REAL(dp), PARAMETER :: VSMOW_17O    =  386.72E-06_dp  ! Assonov, 2003b, pc
  REAL(dp), PARAMETER :: VSMOW_18O    = 2005.20E-06_dp
! oxygen mass-independent fractionation factor
  REAL(dp), PARAMETER :: NMDF_O        = 0.5281_dp      ! meteoric waters
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:O}

! treshold value: below it, species might stop to sink to the others 
! (but can receive still)
  REAL(dp), PARAMETER :: THRES = 1.0E-40_dp * 2.5047E+19_dp  
!                                ?          * mean cair

! -----------------------------------------------------------------------------

! here constants and doubled species indices are to be defined
! {$TRAC_DECL} [%ind_#%] <-- boxmodel syntax  (%{%TAG}_#%) <-- isotracers syntax

! -----------------------------------------------------------------------------
  
! no. of "rejected" species (under threshold)
  INTEGER             :: {%DBL}_NREJCT

->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:C}
! output array: doubled carbons: 2 species and D13C (+TC)     = (NSPEC+1)*3
!                                TC(regular),                 +1
!                                d0TC(reg), d0TC(iso), d0D13CTC, +3
!                                NREJCT                       +1
  REAL(dp)            :: D{%ATOM}OUT(({%NDSPEC}+1)*(2+1)+1+3+1)
  REAL(dp)            :: D13C({%NDSPEC}), D13CTC
  
! total budget verification
  REAL(dp)            :: TC0, D13CTC0
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:C}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:O}
! output array: doubled oxygen: 3 species, D17O,D18O,DC17O (+TO) = (NSPEC+1)*6
!                               TO(regular),
!                               d0TO(reg),d0TO(iso),d0D17TO,d0D18TO,d0DC17OTO,
!                               NREJCT
  REAL(dp)            :: D{%ATOM}OUT(({%NDSPEC}+1)*(3+3)+1+5+1)
  REAL(dp)            :: D17O({%NDSPEC}), D18O({%NDSPEC}), DC17O({%NDSPEC}), &
                         D17OTO, D18OTO, DC17OTO

! total budget verification
  REAL(dp)            :: TO0, D17OTO0, D18OTO0, DC17OTO0
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:O}

! -----------------------------------------------------------------------------

  PRIVATE NKRSPEC, KRSIND

  PUBLIC {%DBL}_x0
  PUBLIC {%DBL}_emis
  PUBLIC {%DBL}_depos
  PUBLIC {%DBL}_pmix
  PUBLIC {%DBL}_process
  PUBLIC {%DBL}_calctotals
  PUBLIC {%DBL}_calcdeltas
  PUBLIC {%DBL}_correct2reg
  PUBLIC {%DBL}_correct2iso
! PUBLIC {%DBL}_fudge
  PUBLIC {%DBL}_resetPTs
  PUBLIC {%DBL}_init
  PUBLIC {%DBL}_result
  PUBLIC {%DBL}_finish

! ==============================================================================

CONTAINS

! ==============================================================================

  SUBROUTINE {%DBL}_x0
  
    IMPLICIT NONE

  ! tracers mixing ratios initialization (x0)

    INTEGER :: i

->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>CASE:REM}
! {$x0} [%n%]  (%    D13C({%TAG}_#) = $%)
! n - # of the minor class, i.e. 1 for d13 / 1 for d17, 2 for d18
! # - species name; $ - init. value
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<CASE:REM}
  ! initializing isotopologues concentration according to "regular", then
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:C}

! {$x0} [%1%]  (%    D13C({%TAG}_#) = $%)

#ifdef INIUNIT_DELTAPM
  ! 12C, 13C through delta and regular species:

    D13C(:) = D13C(:) / 1000.0_dp         ! de-permilizing

#ifdef ZERO_TEST
    D13C(:) = 0.0_dp
#endif

    C({%RDIND}(:,1)) = C({%RDIND}(:,0)) * &
      isofrac2r(D13C(:), VPDB_13C, QD{%ATOM}ATOM(:))
    C({%RDIND}(:,2)) = C({%RDIND}(:,0)) * &
      isofrac2f(D13C(:), VPDB_13C, QD{%ATOM}ATOM(:))

!    DO i = 1, {%NDSPEC}
!      C({%RDIND}(i,1)) = C({%RDIND}(i,0)) * &
!        isofrac2r(D13C(i), VPDB_13C, QD{%ATOM}ATOM(i))
!      C({%RDIND}(i,2)) = C({%RDIND}(i,0)) * &
!        isofrac2f(D13C(i), VPDB_13C, QD{%ATOM}ATOM(i))
!    ENDDO
#endif

#ifdef INIUNIT_FRACMIN
  ! 12C, 13C through minor fraction and regular species:

#ifdef ZERO_TEST
    D13C(:) = 0.0_dp
#endif
!    C({%RDIND}(:,1)) = C({%RDIND}(:,0)) * (1.0_dp - D13C(:))
!    C({%RDIND}(:,2)) = C({%RDIND}(:,0)) * D13C(:)

!    DO i = 1, {%NDSPEC}
!      C({%RDIND}(i,1)) = C({%RDIND}(i,0)) * (1.0_dp - D13C(i))
!      C({%RDIND}(i,2)) = C({%RDIND}(i,0)) * D13C(i)
!    ENDDO
#endif
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:C}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:O}

! {$x0} [%1%]  (%    D17O({%TAG}_#) = $%)

! {$x0} [%2%]  (%    D18O({%TAG}_#) = $%)

#ifdef INIUNIT_DELTAPM
  ! 16O, 17O, 18O through delta and regular species:

    D17O(:) = D17O(:) / 1000.0_dp         ! de-permilizing
    D18O(:) = D18O(:) / 1000.0_dp

#ifdef ZERO_TEST
    D17O(:) = 0.0_dp
    D18O(:) = 0.0_dp
#endif
    C({%RDIND}(:,1)) = C({%RDIND}(:,0)) * &
      isofrac3r(D17O(:), VSMOW_17O, D18O(:), VSMOW_18O, QD{%ATOM}ATOM(:))
    C({%RDIND}(:,2)) = C({%RDIND}(:,0)) * &
      isofrac3f(D17O(:), VSMOW_17O, D18O(:), VSMOW_18O, QD{%ATOM}ATOM(:))
    C({%RDIND}(:,3)) = C({%RDIND}(:,0)) * &
      isofrac3f(D18O(:), VSMOW_18O, D17O(:), VSMOW_17O, QD{%ATOM}ATOM(:))

!   DO i = 1, {%NDSPEC}
!     C({%RDIND}(i,1)) = C({%RDIND}(i,0)) * &
!       isofrac3r(D17O(i), VSMOW_17O, D18O(i), VSMOW_18O, QD{%ATOM}ATOM(i))
!     C({%RDIND}(i,2)) = C({%RDIND}(i,0)) * &
!       isofrac3f(D17O(i), VSMOW_17O, D18O(i), VSMOW_18O, QD{%ATOM}ATOM(i))
!     C({%RDIND}(i,3)) = C({%RDIND}(i,0)) * &
!       isofrac3f(D18O(i), VSMOW_18O, D17O(i), VSMOW_17O, QD{%ATOM}ATOM(i))
!   ENDDO
#endif

#ifdef INIUNIT_FRACMIN
  ! 16O, 17O, 18O through minor fractions and regular species:

#ifdef ZERO_TEST
    D17O(:) = 0.0_dp
    D18O(:) = 0.0_dp
#endif
    C({%RDIND}(:,1)) = C({%RDIND}(:,0)) * (1.0_dp - (D17O(:) + D18O(:)))
    C({%RDIND}(:,2)) = C({%RDIND}(:,0)) * D17O(:)
    C({%RDIND}(:,3)) = C({%RDIND}(:,0)) * D18O(:)

!   DO i = 1, {%NDSPEC}
!     C({%RDIND}(i,1)) = C({%RDIND}(i,0)) * (1.0_dp - (D17O(i) + D18O(i)))
!     C({%RDIND}(i,2)) = C({%RDIND}(i,0)) * D17O(i)
!     C({%RDIND}(i,3)) = C({%RDIND}(i,0)) * D18O(i)
!   ENDDO
#endif
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:O}

  ! updating total {%ATOM} in the system
    CALL {%DBL}_calctotals
    CALL {%DBL}_calcdeltas
    
    T{%ATOM}0 = C(ind_{%ABBR}T{%ATOM})

->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:C}
    D13CTC0 = D13CTC
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:C}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:O}
    D17OTO0 = D17OTO
    D18OTO0 = D18OTO
    DC17OTO0 = DC17OTO
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:O}

  END SUBROUTINE {%DBL}_x0



! -----------------------------------------------------------------------------

  SUBROUTINE {%DBL}_emis(ind_d, amount, deltas)
 
    IMPLICIT NONE
    
    INTEGER,  INTENT(IN)    :: ind_d
    REAL(dp), INTENT(IN)    :: amount
    REAL(dp), INTENT(IN)    :: deltas(:)

  ! filtering possible dummies
    IF ((ind_d .LT. 1) .OR. (ind_d .GT. {%NDSPEC})) RETURN

! uncomment to manage emission only through {%DBL}
!    C({%RDIND}(ind_d,0)) = C({%RDIND(ind_d,0)) + amount 

->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:C}
    ! 12C
    C({%RDIND}(ind_d,1)) = C({%RDIND}(ind_d,1)) + amount * &
      isofrac2r(deltas(1)/1000.0_dp, VPDB_13C, QD{%ATOM}ATOM(ind_d))
    ! 13C
    C({%RDIND}(ind_d,2)) = C({%RDIND}(ind_d,2)) + amount * &
      isofrac2f(deltas(1)/1000.0_dp, VPDB_13C, QD{%ATOM}ATOM(ind_d))
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:C}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:O}
    C({%RDIND}(ind_d,1)) = C({%RDIND}(ind_d,1)) + amount *  &
      isofrac3r(deltas(1)/1000.0_dp, VSMOW_17O, &
                deltas(2)/1000.0_dp, VSMOW_18O, QD{%ATOM}ATOM(ind_d))
    C({%RDIND}(ind_d,2)) = C({%RDIND}(ind_d,2)) + amount *  &
      isofrac3f(deltas(1)/1000.0_dp, VSMOW_17O, &
                deltas(2)/1000.0_dp, VSMOW_18O, QD{%ATOM}ATOM(ind_d))
    C({%RDIND}(ind_d,3)) = C({%RDIND}(ind_d,3)) + amount *  &
      isofrac3f(deltas(2)/1000.0_dp, VSMOW_18O, &
                deltas(1)/1000.0_dp, VSMOW_17O, QD{%ATOM}ATOM(ind_d))
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:O}

  END SUBROUTINE {%DBL}_emis



! -----------------------------------------------------------------------------

  SUBROUTINE {%DBL}_depos(ind_d, factor)

    IMPLICIT NONE

    INTEGER,  INTENT(IN)    :: ind_d
    REAL(dp), INTENT(IN)    :: factor

  ! filtering possible dummies
    IF ((ind_d .LT. 1) .OR. (ind_d .GT. {%NDSPEC})) RETURN

  ! simple deposition routine, introduces no KIE during the deposition
    
    C({%RDIND}(ind_d,1:{%NISO})) = C({%RDIND}(ind_d,1:{%NISO})) * factor
    
  END SUBROUTINE {%DBL}_depos



! -----------------------------------------------------------------------------

  SUBROUTINE {%DBL}_pmix(TSL, dilF, ind_d, mix_amount, mix_deltas)
 
    IMPLICIT NONE

  ! pseudo-mixing of species ind_d with background concentration mix_amount of
  ! mix_deltas composition within TSL timestep with dilF dilution factor [1/s]
    
    REAL(dp), INTENT(IN)    :: TSL, dilF      ! timestep length, dilution factor 
    INTEGER,  INTENT(IN)    :: ind_d          ! spec. index
    REAL(dp), INTENT(IN)    :: mix_amount     ! backgr. concentration
    REAL(dp), INTENT(IN)    :: mix_deltas(:)  ! backgr. deltas
    REAL(dp)                :: corr, tot

  ! filtering possible dummies
    IF ((ind_d .LT. 1) .OR. (ind_d .GT. {%NDSPEC})) RETURN

  ! buget to correct to
    tot = SUM(C(RD{%A}IND(ind_d,1:{%NISO})))
    corr = tot + ( mix_amount - tot ) * TSL * dilF

  ! emission of background iso-composition
    CALL {%DBL}_emis(ind_d, mix_amount * TSL * dilF, mix_deltas)
    tot = SUM(C(RD{%A}IND(ind_d,1:{%NISO})))

  ! removal preserving current composition
    C(RD{%A}IND(ind_d,1:{%NISO})) = C(RD{%A}IND(ind_d,1:{%NISO})) / tot * corr

  END SUBROUTINE {%DBL}_pmix



! -----------------------------------------------------------------------------

  SUBROUTINE {%DBL}_process

    IMPLICIT NONE

    INTEGER  :: i
    REAL(dp) :: chkamnt

  ! calculating the number of specs falling below THRES
    {%DBL}_NREJCT = 0
    DO i = 1, {%NDSPEC}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:C}
      chkamnt = C({%RDIND}(i,1)) + C({%RDIND}(i,2))
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:C}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:O}
      chkamnt = C({%RDIND}(i,1)) + C({%RDIND}(i,2)) + C({%RDIND}(i,3))
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:O}
      IF (chkamnt .LT. THRES) THEN
        {%DBL}_NREJCT = {%DBL}_NREJCT + 1
!       C(RDCIND(i,0)) = 0.0_dp ! UNDEF
!       C(RDCIND(i,1)) = 0.0_dp ! UNDEF
!       C(RDCIND(i,2)) = 0.0_dp ! UNDEF
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:O}
!       C(RDCIND(i,3)) = 0.0_dp ! UNDEF
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:O}
      ENDIF
    ENDDO           ! ndspec cycle

  ! every-step deltas/totals update
    CALL {%DBL}_calctotals
    CALL {%DBL}_calcdeltas

  END SUBROUTINE {%DBL}_process



! -----------------------------------------------------------------------------

  SUBROUTINE {%DBL}_calctotals

    IMPLICIT NONE

    INTEGER  :: i

! here the number of {%ATOM} atoms only calculated, 
! according to each species composition

->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:C}
!   careful, TC is from regular!
    C(ind_ITC)   = SUM( C({%RDIND}(:,0))*REAL(QDCATOM(:),dp) )
    C(ind_I12TC) = SUM( C({%RDIND}(:,1))*REAL(QDCATOM(:),dp) + &
                        C({%RDIND}(:,2))*REAL(QDCATOM(:)-1,dp) )
    C(ind_I13TC) = SUM( C({%RDIND}(:,2)) )
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:C}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:O}
!   careful, TO is from regular!
    C(ind_ITO)   = SUM( C({%RDIND}(:,0))*REAL(QDOATOM(:),dp) )
    C(ind_I16TO) = SUM( C({%RDIND}(:,1))*REAL(QDOATOM(:),dp) + &
                        (C({%RDIND}(:,2)) + C({%RDIND}(:,3))) * &
                        REAL(QDOATOM(:)-1,dp) )
    C(ind_I17TO) = SUM( C({%RDIND}(:,2)) )
    C(ind_I18TO) = SUM( C({%RDIND}(:,3)) )
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:O}

  END SUBROUTINE {%DBL}_calctotals



! -----------------------------------------------------------------------------

  SUBROUTINE {%DBL}_calcdeltas
 
    IMPLICIT NONE

    INTEGER  :: i
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:C}
    REAL(dp) :: f12C
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:C}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:O}
    REAL(dp) :: f16O
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:O}

->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:C}
  ! calculating new delta-13C values
    DO i = 1, {%NDSPEC}
      IF (C({%RDIND}(i,1)) .GT. 0.0_dp) THEN
!      IF ( ( C({%RDIND}(i,1))+C({%RDIND}(i,2)) ) .GT. THRES) THEN
        D13C(i) = delta2( C({%RDIND}(i,1)), C({%RDIND}(i,2)), & 
                          VPDB_13C, QD{%ATOM}ATOM(i) )
      ELSE
        D13C(i) = UNDEF / 1000.0_dp  ! correct UNDEF value for output in permil
      ENDIF
    ENDDO        ! NISPEC-cycle

    ! total carbon   
    IF (C(ind_I12TC) /= 0.0_dp) THEN
      D13CTC = delta2( C(ind_I12TC),C(ind_I13TC),VPDB_13C,1 )
    ELSE
      D13CTC = UNDEF / 1000.0_dp
    ENDIF
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:C}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:O}
  ! calculating new delta-17O, delta-18O, cap.delta-17O values
    DO i = 1, {%NDSPEC}
      IF (C({%RDIND}(i,1)) .GT. 0.0_dp) THEN
!      IF ( ( C({%RDIND}(i,1))+C({%RDIND}(i,2))+C({%RDIND}(i,3)) ) .GT. THRES) THEN
        D17O(i)  = delta3( C({%RDIND}(i,1)), C({%RDIND}(i,2)), C({%RDIND}(i,3)), &
                           VSMOW_17O, QD{%ATOM}ATOM(i) )
        D18O(i)  = delta3( C({%RDIND}(i,1)), C({%RDIND}(i,3)), C({%RDIND}(i,2)), &
                           VSMOW_18O, QD{%ATOM}ATOM(i) )
        DC17O(i) = D17O(i) - NMDF_O * D18O(i)
      ELSE
        D17O(i)  = UNDEF / 1000.0_dp  ! correct UNDEF value for output in permil
        D18O(i)  = UNDEF / 1000.0_dp
        DC17O(i) = UNDEF / 1000.0_dp
      ENDIF
    ENDDO        ! NISPEC-cycle

    ! total oxygen
    IF (C(ind_I16TO) /= 0.0_dp) THEN
      D17OTO  = delta3( C(ind_I16TO), C(ind_I17TO), C(ind_I18TO), VSMOW_17O, 1 )
      D18OTO  = delta3( C(ind_I16TO), C(ind_I18TO), C(ind_I17TO), VSMOW_18O, 1 )
      DC17OTO = D17OTO - NMDF_O * D18OTO
    ELSE
      D17OTO  = UNDEF / 1000.0_dp
      D18OTO  = UNDEF / 1000.0_dp
      DC17OTO = UNDEF / 1000.0_dp
    ENDIF
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:O}


  END SUBROUTINE {%DBL}_calcdeltas
  


! -----------------------------------------------------------------------------

! correction of total isotopomers budget to "regular" species budget  

  SUBROUTINE {%DBL}_correct2reg

    IMPLICIT NONE

    INTEGER  :: i
    REAL(dp) :: total
   
#ifdef USE_KRSIND
! here is the ver. with corr. of only KIE-rel species to regular
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:C}
    ! correcting only species related to KIE in this meccanism
    DO i = 1, NKRSPEC
      ! whole isotopic carbon
      total = C({%RDIND}(KRSIND(i),1)) + &
              C({%RDIND}(KRSIND(i),2))
      IF (total .LE. 0.0_dp) THEN
        C({%RDIND}(KRSIND(i),1)) = 0.0_dp
        C({%RDIND}(KRSIND(i),2)) = 0.0_dp
      ELSE
        C({%RDIND}(KRSIND(i),1)) = ( C({%RDIND}(KRSIND(i),1)) * & 
                                 C({%RDIND}(KRSIND(i),0)) ) / total
        C({%RDIND}(KRSIND(i),2)) = ( C({%RDIND}(KRSIND(i),2)) * &
                                 C({%RDIND}(KRSIND(i),0)) ) / total
      ENDIF
    ENDDO
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:C}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:O}
    ! correcting only species related to KIE in this meccanism
    DO i = 1, NKRSPEC
      ! whole isotopic oxygen
      total = C({%RDIND}(KRSIND(i),1)) + &
              C({%RDIND}(KRSIND(i),2)) + &
              C({%RDIND}(KRSIND(i),3)) 
      IF (total .LE. 0.0_dp) THEN
        C({%RDIND}(KRSIND(i),1)) = 0.0_dp
        C({%RDIND}(KRSIND(i),2)) = 0.0_dp
        C({%RDIND}(KRSIND(i),3)) = 0.0_dp
      ELSE
        C({%RDIND}(i,1)) = ( C({%RDIND}(KRSIND(i),1)) * &
                         C({%RDIND}(KRSIND(i),0)) ) / total
        C({%RDIND}(i,2)) = ( C({%RDIND}(KRSIND(i),2)) * &
                         C({%RDIND}(KRSIND(i),0)) ) / total
        C({%RDIND}(i,3)) = ( C({%RDIND}(KRSIND(i),3)) * &
                         C({%RDIND}(KRSIND(i),0)) ) / total
      ENDIF
    ENDDO
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:O}
#else
! here is the ver. with corr. of ALL species to regular
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:C}
    DO i = 1, {%NDSPEC}
      ! whole isotopic carbon of selected species
      total = C({%RDIND}(i,1)) + &
              C({%RDIND}(i,2)) 
      IF (total .LE. 0.0_dp) THEN
        C({%RDIND}(i,1)) = 0.0_dp
        C({%RDIND}(i,2)) = 0.0_dp
      ELSE
        C({%RDIND}(i,1)) = ( C({%RDIND}(i,1)) * C({%RDIND}(i,0)) ) / total
        C({%RDIND}(i,2)) = ( C({%RDIND}(i,2)) * C({%RDIND}(i,0)) ) / total
      ENDIF
    ENDDO
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:C}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:O}
    DO i = 1, {%NDSPEC}
      ! whole isotopic oxygen of selected species
      total = C({%RDIND}(i,1)) + &
              C({%RDIND}(i,2)) + &
              C({%RDIND}(i,3)) 
      IF (total .LE. 0.0_dp) THEN
        C({%RDIND}(i,1)) = 0.0_dp
        C({%RDIND}(i,2)) = 0.0_dp
        C({%RDIND}(i,3)) = 0.0_dp
      ELSE
        C({%RDIND}(i,1)) = ( C({%RDIND}(i,0)) * C({%RDIND}(i,1)) ) / total
        C({%RDIND}(i,2)) = ( C({%RDIND}(i,0)) * C({%RDIND}(i,2)) ) / total
        C({%RDIND}(i,3)) = ( C({%RDIND}(i,0)) * C({%RDIND}(i,3)) ) / total
      ENDIF
    ENDDO
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:O}
#endif

  END SUBROUTINE {%DBL}_correct2reg



! -----------------------------------------------------------------------------
  
! correction of "regular" species budget to the total isotopologues budget

  SUBROUTINE {%DBL}_correct2iso

    IMPLICIT NONE

    INTEGER  :: i

#ifdef USE_KRSIND
! here is the ver. with corr. of only KIE-rel species to regular
    DO i = 1, NKRSPEC
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:C}
      C({%RDIND}(KRSIND(i),0)) = C({%RDIND}(KRSIND(i),1)) + &
                               C({%RDIND}(KRSIND(i),2))
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:C}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:O}
      C({%RDIND}(KRSIND(i),0)) = C({%RDIND}(KRSIND(i),1)) + &
                             ( C({%RDIND}(KRSIND(i),2)) + &
                               C({%RDIND}(KRSIND(i),3)) )
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:O}
    ENDDO
#endif
#ifndef USE_KRSIND
! here is the ver. with corr. of ALL species to regular
    DO i = 1, {%NDSPEC}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:C}
      C({%RDIND}(i,0)) = C({%RDIND}(i,1)) + &       
                       C({%RDIND}(i,2))
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:C}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:O}
      C({%RDIND}(i,0)) = C({%RDIND}(i,1)) + &
                     ( C({%RDIND}(i,2)) + &
                       C({%RDIND}(i,3)) )
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:O}
    ENDDO
#endif

  END SUBROUTINE {%DBL}_correct2iso



! -----------------------------------------------------------------------------
  
  SUBROUTINE {%DBL}_resetPTs

  ! production tracers initialization (reset) routine

    IMPLICIT NONE
    
! {x$RESET_PTs}
! - currently disabled with use of DRPT{%ATOM}IND()

#ifdef USE_PT
    C(DRPT{%ATOM}IND(:)) = 0.0_dp    ! <-- boxmodel syntax
#endif

  END SUBROUTINE {%DBL}_resetPTs



! -----------------------------------------------------------------------------

! output file for doubled species info
  SUBROUTINE {%DBL}_init

    IMPLICIT NONE

! TODO: put additional tracers/variables+units after INIT_TRAC, INIT_UNIT

    CALL open_output_file(ncid_{%DBL}, 'caaba_mecca_{%DBL}', &
      (/   &
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:C}
! {$TAG_SPECS} [%I12#%]
       , &
! {$TAG_SPECS} [%I13#%]
       , &
! {$TAG_SPECS} [%d13#%]
       , &
{$ELSA}       'TC_R', 'I12TC', 'I13TC', 'd13TC' &
       , &
{$ELSA}       'd0TC_R', 'd0TC', 'd0D13TC' &
       , &
{$ELSA}       'NREJCT' &
       /), (/   &
! {$TAG_SPECS} [%mol/mol%]
       , &
! {$TAG_SPECS} [%mol/mol%]
       , &
! {$TAG_SPECS} [%o/oo%]
       , &
{$ELSA}       'atoms', 'atoms', 'atoms', 'o/oo' &
       , &
{$ELSA}       'atoms', 'atoms', 'o/oo' &
       , &
{$ELSA}       'specs' &
       /), (/   &
! {$TAG_SPECS} [%@SR^1^2#%]
       , &
! {$TAG_SPECS} [%@SR^1^3#%]
       , &
! {$TAG_SPECS} [%@SGd@SR^1^3C(#)%]
       , &
{$ELSA}       '@SRTC_R (regular mech)', '@SRT^1^2C', '@SRT^1^3C', '@SGd@SR^1^3C(TC)' &
       , &
{$ELSA}       '@SGD@SR_t_0(TC_R)', '@SGD@SR_t_0(TC_D)', '@SGD@SR_t_0(@SGd@SR^1^3C(TC_D)) ' &
       , &
{$ELSA}       '@SRnumber of rejected species' &
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:C}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:O}
! {$TAG_SPECS} [%I16#%]
       , &
! {$TAG_SPECS} [%I17#%]
       , &
! {$TAG_SPECS} [%I18#%]
       , &
! {$TAG_SPECS} [%d18#%]
       , &
! {$TAG_SPECS} [%d17#%]
       , &
! {$TAG_SPECS} [%DC17#%]
       , &
{$ELSA}       'TO_R', 'I16TO', 'I17TO', 'I18TO', &
{$ELSA}       'd18TO', 'd17TO', 'DC17TO' &
       , &
{$ELSA}       'd0TO_R', 'd0TO', &
{$ELSA}       'd0D18TO', 'd0D17TO', 'd0DC17TO' &
       , &
{$ELSA}       'NREJCT' &
       /), (/   &
! {$TAG_SPECS} [%mol/mol%]
       , &
! {$TAG_SPECS} [%mol/mol%]
       , &
! {$TAG_SPECS} [%mol/mol%]
       , &
! {$TAG_SPECS} [%o/oo%]
       , &
! {$TAG_SPECS} [%o/oo%]
       , &
! {$TAG_SPECS} [%o/oo%]
       , &
{$ELSA}       'atoms', 'atoms', 'atoms', 'atoms', &
{$ELSA}       'o/oo', 'o/oo', 'o/oo' &
       , &
{$ELSA}       'atoms', 'atoms', &
{$ELSA}       'o/oo', 'o/oo', 'o/oo' &
       , &
{$ELSA}       'specs'  &
       /), (/   &
! {$TAG_SPECS} [%@SR^1^6#%]
       , &
! {$TAG_SPECS} [%@SR^1^7#%]
       , &
! {$TAG_SPECS} [%@SR^1^8#%]
       , &
! {$TAG_SPECS} [%@SGd@SR^1^8O(#)%]
       , &
! {$TAG_SPECS} [%@SGd@SR^1^7O(#)%]
       , &
! {$TAG_SPECS} [%@SGD@SR^1^7O(#)%]
       , &
{$ELSA}       '@SRTO_R', '@SRT^1^6O', '@SRT^1^7O', '@SRT^1^8O', &
{$ELSA}       '@SGd@SR^1^8O(TO)', '@SGd@SR^1^7O(TO)', '@SGD@SR^1^7O(TO)' &
       , &
{$ELSA}       '@SGD@SR_t_0(TO_R)', '@SGD@SR_t_0(TO_D)', &
{$ELSA}       '@SGD@SR_t_0(@SGd@SR^1^8O(TO_D))', '@SGD@SR_t_0(@SGd@SR^1^7O(TO_D))', '@SGD@SR_t_0(@SGD@SR^1^7O(TO_D))' &
       , &
{$ELSA}       '@SRnumber of rejected species'  &
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:O}
       /) )

  END SUBROUTINE {%DBL}_init



! -----------------------------------------------------------------------------

  SUBROUTINE {%DBL}_result(model_time)
  
    IMPLICIT NONE
    
    REAL(dp), INTENT(IN) :: model_time
    INTEGER              :: i
    
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:C}
    DO i = 1, {%NDSPEC}
      D{%A}OUT(i)           = C({%RDIND}(i,1))/cair
      D{%A}OUT({%NDSPEC}+i)   = C({%RDIND}(i,2))/cair
      D{%A}OUT({%NDSPEC}*2+i) = D13C(i) * 1000.0_dp
    ENDDO

  ! totals
    D{%A}OUT({%NDSPEC}*3+1) = C(ind_ITC)
    D{%A}OUT({%NDSPEC}*3+2) = C(ind_I12TC)
    D{%A}OUT({%NDSPEC}*3+3) = C(ind_I13TC)
    D{%A}OUT({%NDSPEC}*3+4) = D13CTC * 1000.0_dp

  ! totals verification
    D{%A}OUT({%NDSPEC}*3+5) = C(ind_ITC)-TC0                   ! d0TC_R   = TC_R - TC_R(t=0)
    D{%A}OUT({%NDSPEC}*3+6) = (C(ind_I12TC)+C(ind_I13TC))-TC0  ! d0TC     = (T12C+T13C) - TC_R(t=0)
    D{%A}OUT({%NDSPEC}*3+7) = (D13CTC-D13CTC0) * 1000.0_dp     ! d0D13CTC = D13CTC - D13CTC(t=0)   
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:C}
->>- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {>ATOM:O}
    DO i = 1, {%NDSPEC}
      D{%A}OUT(i)           = C({%RDIND}(i,1))/cair
      D{%A}OUT({%NDSPEC}+i)   = C({%RDIND}(i,2))/cair
      D{%A}OUT({%NDSPEC}*2+i) = C({%RDIND}(i,3))/cair
      D{%A}OUT({%NDSPEC}*3+i) = D18O(i) * 1000.0_dp
      D{%A}OUT({%NDSPEC}*4+i) = D17O(i) * 1000.0_dp
      D{%A}OUT({%NDSPEC}*5+i) = DC17O(i) * 1000.0_dp
    ENDDO

  ! totals
    D{%A}OUT({%NDSPEC}*6+1) = C(ind_ITO)
    D{%A}OUT({%NDSPEC}*6+2) = C(ind_I16TO)
    D{%A}OUT({%NDSPEC}*6+3) = C(ind_I17TO)
    D{%A}OUT({%NDSPEC}*6+4) = C(ind_I18TO)
    D{%A}OUT({%NDSPEC}*6+5) = D18OTO * 1000.0_dp
    D{%A}OUT({%NDSPEC}*6+6) = D17OTO * 1000.0_dp
    D{%A}OUT({%NDSPEC}*6+7) = DC17OTO * 1000.0_dp

  ! totals verification
    D{%A}OUT({%NDSPEC}*6+8) = C(ind_ITO)-TO0                   ! d0TO_R    = TO_R - TO_R(t=0)
    D{%A}OUT({%NDSPEC}*6+9) = C(ind_I16TO)+C(ind_I17TO)+C(ind_I18TO)-TO0  ! d0TO = (T16O+T17O+T18O) - TO_R(t=0)
    D{%A}OUT({%NDSPEC}*6+10) = (D18OTO-D18OTO0) * 1000.0_dp    ! d0D18OTO  = D18OTO - D18OTO(t=0)
    D{%A}OUT({%NDSPEC}*6+11) = (D17OTO-D17OTO0) * 1000.0_dp    ! d0D18OTO  = D17OTO - D17OTO(t=0)
    D{%A}OUT({%NDSPEC}*6+12) = (DC17OTO-DC17OTO0) * 1000.0_dp  ! d0DC17OTO = DC17OTO - DC18OTO(t=0)
-<<- תתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתתת {<ATOM:O}

  ! last value is a common parameter
    D{%A}OUT(UBOUND(D{%A}OUT)) = REAL({%DBL}_NREJCT)


    CALL write_output_file(ncid_{%DBL}, model_time, D{%A}OUT)

  END SUBROUTINE {%DBL}_result



! -----------------------------------------------------------------------------

  SUBROUTINE {%DBL}_finish

    CALL close_file(ncid_{%DBL})

  END SUBROUTINE {%DBL}_finish



! - some cfg cheks ------------------------------------------------------------

#ifndef INIUNIT_DELTAPM
#ifndef INIUNIT_FRACMIN
#ifndef ZERO_TEST
#ifndef NULL_TEST
 FATAL: initialization is not defined, check the parameters
#endif
#endif
#endif
#endif

! -----------------------------------------------------------------------------
  
END MODULE messy_mecca_{%DBL}_box

! *****************************************************************************

