! ==============================================================================
! {%CMODEL}_dbl_box
! generated: {%TIMEDATE}
!
! this module is generated by imtag utility
!
! inter-configuration driver module
! level: boxmodel
!
! {$DBL_INFO} ! this is a template for isotopes configuration
!
! [Gromov, MPI-C, 2007-2008]
! ==============================================================================

! - general doubling parameters (as conditional defines) -----------------------

#include "{%CMODEL}_dbl_parameters.inc"

! -----------------------------------------------------------------------------

MODULE {%CMODEL}_dbl_box

  USE messy_mecca_kpp ! dp, ...

! configurations linked
! {$CONF_LIST} [%  USE {%CMODEL}_#_box%]

  IMPLICIT NONE

  PUBLIC dbl_emis
  PUBLIC dbl_process     ! substitutes calc totals/deltas/fractions
  PUBLIC dbl_resetPTs
  PUBLIC dbl_init
  PUBLIC dbl_result
  PUBLIC dbl_finish

! =============================================================================

CONTAINS

! -----------------------------------------------------------------------------

  SUBROUTINE dbl_x0
  
    IMPLICIT NONE

! {$CONF_LIST} [%    CALL #_x0%]

#ifdef DEBUG
    print *,'dbl_x0: passed'
#endif 

  END SUBROUTINE dbl_x0



! -----------------------------------------------------------------------------

  SUBROUTINE dbl_emis
 
    IMPLICIT NONE
    
  ! TODO: emissions code for all configurations can be introduced here

  ! z.B.
  ! #ifdef dbl_IC
  !   dbl_IC_emis(dbl_IC_CH4, 1.0E-9*cair, -52.6_dp+2.6_dp)
  ! #endif
  
#ifdef DEBUG
    print *,'dbl_emis: passed'
#endif 

  END SUBROUTINE dbl_emis



! -----------------------------------------------------------------------------

  SUBROUTINE dbl_process

    IMPLICIT NONE

! {$CONF_LIST} [%    CALL #_process%]

  ! by default, to remove deviation due to KIEs, correcting
! {$CONF_LIST} [%    CALL #_correct2reg%]

#ifdef DEBUG
    print *,'dbl_process: passed'
#endif 

  END SUBROUTINE dbl_process



! -----------------------------------------------------------------------------
 
  SUBROUTINE dbl_resetPTs
  
    IMPLICIT NONE
    
! {$CONF_LIST} [%    CALL #_resetPTs %]

#ifdef DEBUG
    print *,'dbl_resetPTs: passed'
#endif 

  END SUBROUTINE dbl_resetPTs


! -----------------------------------------------------------------------------

  SUBROUTINE dbl_init

    IMPLICIT NONE

    CALL dbl_x0

! {$CONF_LIST} [%    CALL #_init%]
  
#ifdef DEBUG
    print *,'dbl_init: passed'
#endif 

  END SUBROUTINE dbl_init



! -----------------------------------------------------------------------------

  SUBROUTINE dbl_result(model_time)
  
    IMPLICIT NONE
    
    REAL(dp), INTENT(IN) :: model_time
    
! {$CONF_LIST} [%    CALL #_result(model_time)%]

#ifdef DEBUG
    print *,'dbl_result: passed'
#endif 

  END SUBROUTINE dbl_result



! ---------------------------------------------------------------------------

  SUBROUTINE dbl_finish

! {$CONF_LIST} [%    CALL #_finish%]

#ifdef DEBUG
    print *,'dbl_finish: passed'
#endif 

  END SUBROUTINE dbl_finish



! ---------------------------------------------------------------------------

END MODULE {%CMODEL}_dbl_box

! ***************************************************************************

