! ==============================================================================
! {%CMODEL}_dbl_box
! generated: {%TIMEDATE}
!
! this module is generated by imtag utility
!
! inter-configuration driver module
! level: boxmodel
!
! {$DBL_INFO} ! this is a template for isotopes configuration
!
! [Gromov, MPI-C, 2007-2008]
! ==============================================================================

! - general doubling parameters (as conditional defines) -----------------------

#include "{%CMODEL}_dbl_parameters.inc"

! -----------------------------------------------------------------------------

MODULE {%CMODEL}_dbl_si

  USE messy_mecca_kpp, ONLY: dp

! configurations linked
! {$CONF_LIST} [%  USE {%CMODEL}_#\n  USE {%CMODEL}_#_si\n%]

  IMPLICIT NONE

  INTEGER, PARAMETER      :: is = 1
  PRIVATE is

  PUBLIC mecca_dbl_postprocess      ! substitutes calc totals/deltas/fractions
  PUBLIC mecca_dbl_resetPTs
  PUBLIC mecca_dbl_init
  PUBLIC mecca_dbl_result
  PUBLIC mecca_dbl_finish

! =============================================================================

CONTAINS

! -----------------------------------------------------------------------------

  SUBROUTINE mecca_dbl_postprocess(Conc)

    USE messy_main_timer, ONLY: lstart
#ifndef MESSYTIMER
    USE messy_main_data_bi, & 
#else
    USE messy_main_timer,   &
#endif
      ONLY: lstart, current_time_step

    IMPLICIT NONE

    REAL(dp), INTENT(INOUT) :: Conc(:,:)

! {$COasNF_LIST} [%    CALL #_process%] this is to call when iso_si will be ready

  ! skipped: calculating the number of specs falling below THRES

  ! every-configuration totals update
! {$CONF_LIST} [%    CALL #_calctotals(Conc(:,is)) %]

  ! by default, to remove deviation due to KIEs, correcting
! {$CONF_LIST} [%    CALL #_correct2reg(Conc(:,is)) %]

! improperly initializing configurations here :-0
    IF ((lstart) .OR. (current_time_step .LT. 4)) THEN
! {$CONF_LIST} [%      CALL #_x1(Conc(:,is))%]
      print *,'mecca_dbl_postprocess(e5): x1 event triggered'
      print *,'CTS = ',current_time_step,', lstart = ',lstart
    ENDIF


#ifdef DEBUG
    print *,'mecca_dbl_postprocess(e5): passed'
#endif 

  END SUBROUTINE mecca_dbl_postprocess



! -----------------------------------------------------------------------------
 
  SUBROUTINE mecca_dbl_resetPTs(Conc)
  
    IMPLICIT NONE
    
    REAL(dp), INTENT(INOUT) :: Conc(:,:)

! {$CONF_LIST} [%    CALL #_resetPTs(Conc(:,is))%]

#ifdef DEBUG
    print *,'mecca_dbl_resetPTs: passed'
#endif 

  END SUBROUTINE mecca_dbl_resetPTs


! -----------------------------------------------------------------------------

  SUBROUTINE mecca_dbl_init(Conc)

    IMPLICIT NONE

    REAL(dp), INTENT(INOUT) :: Conc(:,:)

  ! some routines for configuration initialization can be called here

  END SUBROUTINE mecca_dbl_init



! -----------------------------------------------------------------------------

  SUBROUTINE mecca_dbl_result(model_time)
  
    IMPLICIT NONE
    
    REAL(dp), INTENT(IN) :: model_time
    
  ! routines for additional data output (e5) for configurations to be here

#ifdef DEBUG
    print *,'mecca_dbl_result: passed'
#endif 

  END SUBROUTINE mecca_dbl_result



! ---------------------------------------------------------------------------

  SUBROUTINE mecca_dbl_finish

#ifdef DEBUG
    print *,'mecca_dbl_finish: passed'
#endif 

  END SUBROUTINE mecca_dbl_finish



! ---------------------------------------------------------------------------

END MODULE {%CMODEL}_dbl_si

! ***************************************************************************

