! ==============================================================================
! {%DBL}_box
! generated: {%TIMEDATE}
!
! this module is automaticly generated by imdouble utility
! contains: some maintenance routines for budgeting configurations (isotopes)
! level: boxmodel
!
! {$DBL_INFO} ! this is a template file for imdouble utility
!
! [Gromov, MPIC, 2007-2008]
! ==============================================================================

! - general doubling parameters (as conditional defines) -----------------------

#include "{%CMODEL}_dbl_parameters.inc"

! WARNING: THIS IS A TEMPORARY PROTOTYPE 

! ------------------------------------------------------------------------------

! {$CONF_PARAM}

MODULE {%CMODEL}_{%DBL}_si

  USE messy_mecca_kpp, ONLY: dp
  USE {%CMODEL}_dbl_common
  USE {%CMODEL}_{%DBL}

->>- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ {>ATOM:C}
! reference standart ratio for 13C, V-PDB
  REAL(dp), PARAMETER :: VPDB_13C     = 1123.72E-05_dp
-<<- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ {<ATOM:C}
->>- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ {>ATOM:O}
! reference standart ratio for 17O, 18O, V-SMOW
  REAL(dp), PARAMETER :: VSMOW_17O    =  386.72E-06_dp  ! Assonov, 2003b, pc
  REAL(dp), PARAMETER :: VSMOW_18O    = 2005.20E-06_dp
! oxygen mass-independent fractionation factor
  REAL(dp), PARAMETER :: NMDF_O        = 0.5281_dp      ! beta: meteoric waters
-<<- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ {<ATOM:O}

  PUBLIC {%DBL}_x1

! ==============================================================================

CONTAINS

! -----------------------------------------------------------------------------

->>- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ {>CASE:REM}
! {$x0} [%n%]  (%    D13C({%TAG}_#) = $%)
! n - # of the minor class, i.e. 1 for d13 / 1 for d17, 2 for d18
! # - species name; $ - init. value
-<<- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ {<CASE:REM}

! tracers mixing ratios initialization (x1) -- temp. for e5

  SUBROUTINE {%DBL}_x1(C)
  
    IMPLICIT NONE

    REAL(dp), INTENT(INOUT) :: C(:)

    INTEGER  :: i
->>- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ {>ATOM:C}
    REAL(dp) :: D13C(1:{%NDSPEC})

! {$x0} [%1%]  (%    D13C({%DBL}_#) = $%)

#ifdef INIUNIT_DELTAPM
  ! 12C, 13C through delta and regular species:

    D13C(:) = D13C(:) / 1000.0_dp         ! de-permilizing

#ifdef ZERO_TEST
    D13C(:) = 0.0_dp
#endif

    C({%RDIND}(:,1)) = C({%RDIND}(:,0)) * &
      isofrac2r(D13C(:), VPDB_13C, QD{%ATOM}ATOM(:))
    C({%RDIND}(:,2)) = C({%RDIND}(:,0)) * &
      isofrac2f(D13C(:), VPDB_13C, QD{%ATOM}ATOM(:))

!    DO i = 1, {%NDSPEC}
!      C({%RDIND}(i,1)) = C({%RDIND}(i,0)) * &
!        isofrac2r(D13C(i), VPDB_13C, QD{%ATOM}ATOM(i))
!      C({%RDIND}(i,2)) = C({%RDIND}(i,0)) * &
!        isofrac2f(D13C(i), VPDB_13C, QD{%ATOM}ATOM(i))
!    ENDDO
#endif

#ifdef INIUNIT_FRACMIN
  ! 12C, 13C through minor fraction and regular species:

#ifdef ZERO_TEST
    D13C(:) = 0.0_dp
#endif
!    C({%RDIND}(:,1)) = C({%RDIND}(:,0)) * (1.0_dp - D13C(:))
!    C({%RDIND}(:,2)) = C({%RDIND}(:,0)) * D13C(:)

!    DO i = 1, {%NDSPEC}
!      C({%RDIND}(i,1)) = C({%RDIND}(i,0)) * (1.0_dp - D13C(i))
!      C({%RDIND}(i,2)) = C({%RDIND}(i,0)) * D13C(i)
!    ENDDO
#endif
-<<- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ {<ATOM:C}
->>- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ {>ATOM:O}
    REAL(dp) :: D17O(1:{%NDSPEC}), D18O(1:{%NDSPEC})

! {$x0} [%1%]  (%    D17O({%DBL}_#) = $%)

! {$x0} [%2%]  (%    D18O({%DBL}_#) = $%)

#ifdef INIUNIT_DELTAPM
  ! 16O, 17O, 18O through delta and regular species:

    D17O(:) = D17O(:) / 1000.0_dp         ! de-permilizing
    D18O(:) = D18O(:) / 1000.0_dp

#ifdef ZERO_TEST
    D17O(:) = 0.0_dp
    D18O(:) = 0.0_dp
#endif
    C({%RDIND}(:,1)) = C({%RDIND}(:,0)) * &
      isofrac3r(D17O(:), VSMOW_17O, D18O(:), VSMOW_18O, QD{%ATOM}ATOM(:))
    C({%RDIND}(:,2)) = C({%RDIND}(:,0)) * &
      isofrac3f(D17O(:), VSMOW_17O, D18O(:), VSMOW_18O, QD{%ATOM}ATOM(:))
    C({%RDIND}(:,3)) = C({%RDIND}(:,0)) * &
      isofrac3f(D18O(:), VSMOW_18O, D17O(:), VSMOW_17O, QD{%ATOM}ATOM(:))

!   DO i = 1, {%NDSPEC}
!     C({%RDIND}(i,1)) = C({%RDIND}(i,0)) * &
!       isofrac3r(D17O(i), VSMOW_17O, D18O(i), VSMOW_18O, QD{%ATOM}ATOM(i))
!     C({%RDIND}(i,2)) = C({%RDIND}(i,0)) * &
!       isofrac3f(D17O(i), VSMOW_17O, D18O(i), VSMOW_18O, QD{%ATOM}ATOM(i))
!     C({%RDIND}(i,3)) = C({%RDIND}(i,0)) * &
!       isofrac3f(D18O(i), VSMOW_18O, D17O(i), VSMOW_17O, QD{%ATOM}ATOM(i))
!   ENDDO
#endif

#ifdef INIUNIT_FRACMIN
  ! 16O, 17O, 18O through minor fractions and regular species:

#ifdef ZERO_TEST
    D17O(:) = 0.0_dp
    D18O(:) = 0.0_dp
#endif
    C({%RDIND}(:,1)) = C({%RDIND}(:,0)) * (1.0_dp - (D17O(:) + D18O(:)))
    C({%RDIND}(:,2)) = C({%RDIND}(:,0)) * D17O(:)
    C({%RDIND}(:,3)) = C({%RDIND}(:,0)) * D18O(:)

!   DO i = 1, {%NDSPEC}
!     C({%RDIND}(i,1)) = C({%RDIND}(i,0)) * (1.0_dp - (D17O(i) + D18O(i)))
!     C({%RDIND}(i,2)) = C({%RDIND}(i,0)) * D17O(i)
!     C({%RDIND}(i,3)) = C({%RDIND}(i,0)) * D18O(i)
!   ENDDO
#endif
-<<- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ {<ATOM:O}

#ifdef NULL_TEST
    C({%RDIND}(:,1)) = C({%RDIND}(:,0))
    DO i = 2, {%NDSPEC}
      C({%RDIND}(:,i)) = 0.0_dp
    ENDDO
#endif

  ! updating total {%ATOM} in the system
    CALL {%DBL}_calctotals(C)
    
  END SUBROUTINE {%DBL}_x1


! -----------------------------------------------------------------------------
  
END MODULE {%CMODEL}_{%DBL}_si

! *****************************************************************************

